name: DIANA: Lint Workflows

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: ğŸ§ª Check GitHub workflows with actionlint
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Install actionlint
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint-linux-amd64.gz | gunzip -c > actionlint
          chmod +x actionlint
          sudo mv actionlint /usr/local/bin/

      - name: ğŸ” Run actionlint on workflows
        run: |
          actionlint -color
